### PR TITLE
fix(react): update DevMode simply

### LINKED ISSUE #479: Note to remember idea: how about make each Suspense, ErrorBoundary contain DevMode
Note to remember idea: how about make each Suspense, ErrorBoundary contain DevMode

_Originally posted by @manudeli in https://github.com/suspensive/react/issues/470#issuecomment-1857345944_

### PR DESCRIPTION
**Pull request by manudeli**
fix #479 

# Overview

@minsoo-web I reflect our discussion. Always thanks for your great feedback.

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/suspensive/react/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

File: packages/react/src/DevMode.tsx [hunk 1]
```diff
@@ -1,115 +1,110 @@
...
+  /**
+   * @experimental This is experimental feature.
+   */
+  devMode?: TDevModeProps
+}
 
 type Sync = () => void
 class SuspensiveDevMode {
-  constructor(public is = process.env.NODE_ENV !== 'production') {}
+  constructor(public is = false) {}
```
Comment (manudeli) [inline packages/react/src/DevMode.tsx:19]: suspensiveDevMode.is defaultly
