### PR TITLE
fix(react): fix throw null

### LINKED ISSUE #141: [BUG]: throw null as error case
### **Package Scope**

Package name: @suspensive/react

### PR DESCRIPTION
**Pull request by manudeli**
fix #141 
related with #62

# ErrorBoundary should catch null thrown by children
I also added test case for it

## PR Checklist

- [x] I have written documents and tests, if needed.

### CODE REVIEW

File: packages/react/src/utils/toTest.tsx [hunk 1]
```diff
@@ -29,6 +29,19 @@ export const ThrowError = ({ message, after, children }: ThrowErrorProps) => {
...
+
+type ThrowNullProps = PropsWithChildren<{ after: number }>
+export const ThrowNull = ({ after, children }: ThrowNullProps) => {
+  const [isNeedError, setIsNeedError] = useState(throwErrorIsNeed.current)
+  if (isNeedError) {
+    throw null
+  }
+  useEffect(() => {
+    setTimeout(() => setIsNeedError(true), after)
+  }, [after])
```
Comment (tooooo1) [inline packages/react/src/utils/toTest.tsx:41]:
```suggestion
  useEffect(() => {
    const timerId = setTimeout(() => setIsNeedError(true), after)

    return () => {
      clearTimeout(timerId)
    }
  }, [after])
```

Cleanup 😁

Comment (manudeli) [reply packages/react/src/utils/toTest.tsx]: Cool!

**Review by tooooo1 — APPROVED** [review]

**Review by okinawaa — APPROVED** [review]
