### PR TITLE
fix(react): Improve Await

### LINKED ISSUE #80: [BUG]: fix useSuspenseCache tearing with startTransition, adopt useSyncExternalStore
### **Package Scope**

- [x] Add to an existing package

Package name: @suspensive/react

### **Overview**

https://github.com/reactwg/react-18/discussions/86

Implement fixing with compatiable react 17 or under with this library
https://www.npmjs.com/package/use-sync-external-store

#### Reference
react-redux's solution https://github.com/reduxjs/react-redux/blob/master/package.json#L77

### LINKED ISSUE #149: [BUG]: AwaitOption key's field order is matter because of JSON.stringify care field's order
### **Package Scope**

Package name: @suspensive/react

### PR DESCRIPTION
**Pull request by manudeli**
fix #80
fix #149 

# Improve Await

## 1. Replace useEffect to use-sync-external-store
I replaced useEffect to resolve tearing issue on Concurrent Rendering for External Store Libraries like us [This React Conf Session by Daishi Kato](https://conf.reactjs.org/stage) inspire me why we change useEffect to sync our awaitClient to react
image

## 2. Use hashKey 
To ignore object field's order for key of AwaitOptions
So I added hashKey and test code for it

## PR Checklist

- [x] I have written documents and tests, if needed.

### CODE REVIEW

File: packages/react/src/experimental/Await.tsx [hunk 1]
```diff
@@ -1,164 +1,168 @@
...
-  data?: unknown
-}
+export const Await = <TData, TKey extends Key>({ children, options }: AwaitProps<TData, TKey>) =>
+  createElement(children, useAwait<TData, TKey>(options))
 
-class SuspensiveCacheObserver {
-  private cache = new Map<string, Cache>()
+class AwaitClient {
+  private cache = new Map<ReturnType<typeof hashKey>, AwaitState>()
+  private syncsMap = new Map<ReturnType<typeof hashKey>, ((...args: unknown[]) => unknown)[]>()
```
Comment (tooooo1) [inline packages/react/src/experimental/Await.tsx:62]:
```suggestion
  private syncsMap = new Map<ReturnType<typeof hashKey>, Sync[]>()
```

File: packages/react/src/utils/hashKey.ts [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+          .reduce((result, key) => {
+            result[key] = val[key]
+            return result
+          }, {} as any)
+      : val
+  )
+}
+
+// eslint-disable-next-line @typescript-eslint/ban-types
+const isPlainObject = (o: any): o is Object => {
```
Comment (tooooo1) [inline packages/react/src/utils/hashKey.ts:17]: about **hashing**, wouldn't it be more rigorous to check with `type PlainObject = Record<string, any>` instead of just an object type?

```suggestion
type PlainObject = Record<string, any>

export const hashKey = (key: Key) => {
  return JSON.stringify(key, (_, val) =>
    isPlainObject(val)
      ? Object.keys(val)
          .sort()
          .reduce((result: PlainObject, key) => {
            result[key] = val[key]
            return result
          }, {})
      : val
  )
}

const isPlainObject = (o: any): o is PlainObject => {
```

we can also eliminate the lint directive `// eslint-disable-next-line @typescript-eslint/ban-types`.

File: packages/react/src/utils/hashKey.ts [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+  // eslint-disable-next-line no-prototype-builtins
+  if (!prot.hasOwnProperty('isPrototypeOf')) {
+    return false
+  }
+
+  // Most likely a plain Object
+  return true
+}
+
+const hasObjectPrototype = (o: any) => Object.prototype.toString.call(o) === '[object Object]'
```
Comment (tooooo1) [inline packages/react/src/utils/hashKey.ts:44]:
```suggestion
const hasObjectPrototype = (o: PlainObject) => Object.prototype.toString.call(o) === '[object Object]'
```

File: packages/react/src/utils/hashKey.ts [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+
+  // If has modified prototype
+  const prot = ctor.prototype
+  if (!hasObjectPrototype(prot)) {
+    return false
+  }
+
+  // If constructor does not have an Object-specific method
+  // eslint-disable-next-line no-prototype-builtins
+  if (!prot.hasOwnProperty('isPrototypeOf')) {
```
Comment (tooooo1) [inline packages/react/src/utils/hashKey.ts:36]:
```suggestion
  if (!Object.prototype.hasOwnProperty.call(prot, 'isPrototypeOf')) {
```

By using Object.prototype.hasOwnProperty.call(prot, 'isPrototypeOf'), you've adhered to best practices, ensuring that the method call is safe even if hasOwnProperty is not directly present on the object. As a result, the `// eslint-disable-next-line no-prototype-builtins` comment became redundant and was correctly removed.

File: packages/react/src/experimental/Await.tsx (hunk 1 above)
Comment (manudeli) [reply packages/react/src/experimental/Await.tsx]: Oh I missed it

File: packages/react/src/utils/hashKey.ts (hunk 4 above)
Comment (manudeli) [reply packages/react/src/utils/hashKey.ts]: So cool!

File: packages/react/src/utils/hashKey.ts (hunk 3 above)
Comment (manudeli) [reply packages/react/src/utils/hashKey.ts]: I think hasObjectPrototype don't have to constraint parameter as only `PlainObject` so I didn't follow this suggestion but Good Advice! Thanks!

**Review by tooooo1 — APPROVED** [review]

**Review by okinawaa — CHANGES_REQUESTED** [review]
Cool

**Review by okinawaa — APPROVED** [review]
