### PR TITLE
fix(tsup): add supported browsers

### LINKED ISSUE #442: [Feature]: specify target
### Package Scope

@suspensive/react, @suspensive/react-query, @suspensive/react-await, @suspensive/react-image

### Description

tsup target

### Possible Solution

_No response_

### etc.

_No response_

### PR DESCRIPTION
**Pull request by manudeli**
fix #442 
thanks to @injxgj @sungh0lim @zillako for giving me idea to add this. if you okay approve this Pull Request too.

# Add Supported Browsers

### Extra commit to check our diffs by setting target of tsup for reviewers
I updated [tsup's target](https://tsup.egoist.dev/#target-environment) to specify our supported browsers
We can check what is diff between before and after set target of tsup in [6dd85f0](https://github.com/suspensive/react/pull/455/commits/6dd85f098214f7755b15d108bcbf2e32ed71fe19). I made extra commit to differ them.

image

### Browserslist way (96.7%)
our tsup target is ['chrome51', 'firefox53', 'edge18', 'safari11', 'ios11', 'opera38', 'es6', 'node14']
It's [almost 96.7% audience coverage in browserslist](https://browsersl.ist/#q=%22browserslist%22%3A+%5B%0A++%22defaults%22%2C+%22chrome+%3E%3D+51%22%2C+%22firefox+%3E%3D+53%22%2C+%22edge+%3E%3D+18%22%2C+%22safari+%3E%3D+11%22%2C+%22ios+%3E%3D+11%22%2C+%22opera+%3E%3D+38%22%2C+%22node+%3E%3D+14%22%2C+%22not+dead%22%0A%5D+) I think.

### New section to show Suspensive's [Supported Browsers in Getting Started](https://docs-v1-git-fix-supported-browsers-suspensive.vercel.app/docs/intro)

image

## PR Checklist

- [x] I did below actions if need

1. I read the [Contributing Guide](https://github.com/suspensive/react/blob/main/CONTRIBUTING.md)
2. I added documents and tests.

### CODE REVIEW

File: configs/tsup/src/index.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import type { Options } from 'tsup'
 export const options: Options = {
   banner: { js: '"use client"' },
   format: ['cjs', 'esm'],
-  // target: ['chrome51', 'es6', 'safari11', 'deno1', 'edge18', 'firefox53', 'node12'],
```
Comment (manudeli) [inline configs/tsup/src/index.ts]: Note to prevent misunderstanding: no target in current main. it's just test comment.
only check toDiff directory please.

**Review by minsoo-web — APPROVED** [review]
LGTM! I think it should be added to v2, but I think it should be updated as soon as possible

**Review by zillako — APPROVED** [review]

**Review by gyoungjun — APPROVED** [review]
