### PR TITLE
fix(react): rename useSuspenseCache to useAwait, suspenseCache to suspensiveCache

### LINKED ISSUE #86: [Feature] AwaitClient's methods need to work with index of key with hierarchy
> currently, we use stringified key yet, but next Pull Request, I want to change it suspenseCache's methods need to work with index of key with hierarchy like queryKey of @tanstack/query

I think this is need to be implemented in this Pull Request. so I change this Pull Request as draft. after that, I'll request review

_Originally posted by @manudeli in https://github.com/suspensive/react/issues/83#issuecomment-1596098279_

### PR DESCRIPTION
**Pull request by manudeli**
related #62 

# Rename useSuspenseCache to Await, suspenseCache to suspensiveCache
- useSuspenseCache -> useAwait
- suspenseCache -> suspensiveCache

ps. I added test code for Await, useAwait

## PR Checklist

- [x] I have written documents and tests, if needed.

### CODE REVIEW

**Comment by manudeli** [comment]
> currently, we use stringified key yet, but next Pull Request, I want to change it suspenseCache's methods need to work with index of key with hierarchy like queryKey of @tanstack/query

I think this is need to be implemented in this Pull Request. so I change this Pull Request as draft. after that, I'll request review

File: packages/react/src/experimental/index.ts [hunk 1]
```diff
@@ -0,0 +1 @@
+export { Await, useAwait } from './Await'
```
Comment (manudeli) [inline packages/react/src/experimental/index.ts:1]: We can use experimental features like this

```tsx
import { Await, useAwait } @suspensive/react/experimental
```

**Review by manudeli — COMMENTED** [review]
I commented my intentions

File: websites/visualization/src/app/react/experimental/await/page.tsx [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+    <ErrorBoundary fallback={() => <>error</>}>
+      <Suspense fallback={<>loading...</>}>
+        <Await options={{ key: [2000] as const, fn: asyncFn }}>
+          {(awaited) => (
+            <div>
+              <div>{awaited.data}</div>
+              <div>{awaited.data}</div>
+            </div>
+          )}
+        </Await>
```
Comment (manudeli) [inline websites/visualization/src/app/react/experimental/await/page.tsx:26]: The reason Cache was removed from the name is that `useQuery` of @tanstack/react-query also uses Cache internally, but uses the more important name `Query` to express querying not `Cache`. Therefore, SuspenseCache was also renamed to focus on `awaiting promise` with the corresponding fn `Await`, not `Cache`.

File: packages/react/src/__test__/experimental/Await.spec.tsx [hunk 3]
```diff
@@ -0,0 +1,111 @@
+import { act, render, screen, waitFor } from '@testing-library/react'
```
Comment (okinawaa) [inline packages/react/src/__test__/experimental/Await.spec.tsx:1]: It's not related to this PR, but I have a question!

Is it better to be in a folder with only a test code?
Isn't it better to be as close to the actual implementation as possible according to the principle of locality when maintaining? To look at the implementation and the test code together

Comment (manudeli) [reply packages/react/src/__test__/experimental/Await.spec.tsx:1]: I understood you may mean removing __test__ directory is better
I'll remove __test__ and refactor it after this PR merging or close

File: packages/react/src/experimental/suspensiveCache.tsx [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+          newCache.error = error
+        }),
+    }
+
+    this.cache.set(stringifiedKey, newCache)
+    // eslint-disable-next-line @typescript-eslint/no-throw-literal
+    throw newCache.promise
+  }
+
+  public getData = <TKey extends Tuple>(key: TKey) => this.cache.get(JSON.stringify(key))?.data
```
Comment (okinawaa) [inline packages/react/src/experimental/suspensiveCache.tsx:79]: Don't we need getPromise or getError?!😄

File: packages/react/src/experimental/suspensiveCache.tsx [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+
+  private keyNotifiesMap = new Map<string, ((...args: unknown[]) => unknown)[]>()
+
+  public attach<TKey extends Tuple>(key: TKey, onNotify: (...args: unknown[]) => unknown) {
+    const stringifiedKey = JSON.stringify(key)
+    const keyNotifies = this.keyNotifiesMap.get(stringifiedKey)
+    this.keyNotifiesMap.set(stringifiedKey, [...(keyNotifies ?? []), onNotify])
+
+    const detachSelf = () => this.detach(key, onNotify)
+    return detachSelf
```
Comment (okinawaa) [inline packages/react/src/experimental/suspensiveCache.tsx:89]:
```suggestion
    return { detach } 
```

I think it takes some learning to think the `detachSelf` function with the return of attach. It was a bit unpredictable!(only my think!..😄)
 
Why don't we return it in the form of an object so that the user can see the function name and figure out the role?

File: packages/react/src/experimental/Await.tsx [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+type AwaitProps<TData, TKey extends Tuple> = {
+  options: AwaitOptions<TData, TKey>
+  children: FunctionComponent<Awaited<TData>>
+}
+
+/**
+ * @experimental This is experimental feature.
+ */
+export const Await = <TData, TKey extends Tuple>({ children: Children, options }: AwaitProps<TData, TKey>) => {
```
Comment (okinawaa) [inline packages/react/src/experimental/Await.tsx:45]: The function of `detach` is defined in the `suspensiveCache`, but I wonder if it is not necessary to use it in the Await component

File: packages/react/src/experimental/suspensiveCache.tsx [hunk 7]
```diff
@@ -0,0 +1,113 @@
...
+  private notifyToAttacher = <TKey extends string>(key?: TKey) =>
+    key
+      ? this.keyNotifiesMap.get(key)?.forEach((notify) => notify())
+      : this.keyNotifiesMap.forEach((keyNotifies) => keyNotifies.forEach((notify) => notify()))
+}
+
+/**
+ * @experimental This is experimental feature.
+ */
+export const suspensiveCache = new SuspensiveCacheObserver()
```
Comment (okinawaa) [inline packages/react/src/experimental/suspensiveCache.tsx:113]: cool 👍

File: websites/visualization/src/app/CommonLayout.tsx [hunk 8]
```diff
@@ -10,7 +10,7 @@ export const CommonLayout = ({ children }: PropsWithChildren) => {
   return (
     <>
       <TopNavigation />
-      <Link href="/react/useSuspenseCache">🔗 Experimental Feature: useSuspenseCache</Link>
+      <Link href="/react/await">🔗 Experimental Feature: Await</Link>
```
Comment (okinawaa) [inline websites/visualization/src/app/CommonLayout.tsx:13]:
```suggestion
      <Link href="/react/experimental/await">🔗 Experimental Feature: Await</Link>
```

File: websites/visualization/src/app/react/experimental/await/page.tsx (hunk 2 above)
Comment (okinawaa) [inline websites/visualization/src/app/react/experimental/await/page.tsx:26]: Will children be invisible before `asyncFn` is resolved? 
Does the external `Suspense` handle the loading(pending) process?

File: packages/react/src/experimental/suspensiveCache.tsx [hunk 9]
```diff
@@ -0,0 +1,113 @@
+import { Tuple } from '../types'
+
+type Cache<Key extends Tuple = Tuple> = {
+  promise?: Promise<unknown>
+  key: Key
+  error?: unknown
+  data?: unknown
+}
+
+class SuspensiveCacheObserver {
```
Comment (okinawaa) [inline packages/react/src/experimental/suspensiveCache.tsx:10]: Doesn't the forced reload(cmd + R) of Chrome blow the cache?
Even if I force a reload, the cached data remains.

File: packages/react/src/experimental/Await.tsx (hunk 6 above)
Comment (manudeli) [reply packages/react/src/experimental/Await.tsx:45]: `detach` will be invoked on `useAwait`'s unmount internally

File: README.md [hunk 10]
```diff
@@ -38,7 +38,9 @@ All declarative components to use suspense on both CSR, SSR.
 - Delay
 - SuspensiveProvider
 - HOC(Higher Order Component)s
-- useSuspenseCache, suspenseCache (Experimental)
+- useAwait, Await (Experimental)
+
+- HOC(Higher Order Component)s
```
Comment (manudeli) [inline README.md:43]:
```suggestion
- useAwait, Await (Experimental)
```

File: websites/visualization/src/app/react/experimental/await/page.tsx (hunk 2 above)
Comment (manudeli) [reply websites/visualization/src/app/react/experimental/await/page.tsx:26]: Yeah, That's right! and this will be cached in cachekey. we can reuse

File: packages/react/src/experimental/suspensiveCache.tsx (hunk 4 above)
Comment (manudeli) [reply packages/react/src/experimental/suspensiveCache.tsx:79]: Let's make another features after this PR

File: packages/react/src/experimental/suspensiveCache.tsx (hunk 9 above)
Comment (manudeli) [reply packages/react/src/experimental/suspensiveCache.tsx:10]: chrome will blow cache on reload. did you test it in Next.js 13? if right, I guess you meet already suspensed data in server without meeting Suspense's fallback

File: packages/react/src/experimental/suspensiveCache.tsx (hunk 5 above)
Comment (manudeli) [reply packages/react/src/experimental/suspensiveCache.tsx]: Beautiful! I think it will make `suspensive.attach` more extendable by object with naming clarity

File: packages/react/src/experimental/suspensiveCache.tsx (hunk 9 above)
Comment (okinawaa) [reply packages/react/src/experimental/suspensiveCache.tsx:10]: Oh i understood
It works in server i think!

**Review by okinawaa — APPROVED** [review]
Cool

File: .changeset/plenty-mayflies-cry.md [hunk 11]
```diff
@@ -0,0 +1,5 @@
+---
+'@suspensive/react': patch
```
Comment (manudeli) [inline .changeset/plenty-mayflies-cry.md:2]:
```suggestion
'@suspensive/react': minor
```
